<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<form id="repo_form">
    <label for="repo">Source Repository:</label>
    https://github.com/<input style="width: 200px" name="repo" id="repo" type="text" title="Source Repository"/>
    <button>Submit</button>
</form>

<script type="application/javascript">
    let form = document.getElementById("repo_form");
    form.addEventListener("submit", function(event) {
        let repo = document.getElementById("repo").value;
        event.preventDefault();

        if (repo) {
            window.open("/repo/" + repo);
        }
    });
</script>
