<?php
/**
 * @var string $clientId
 */
$this->layout('layout::default', ['title' => 'Login']);
?>

<div class="jumbotron">
    <h1 class="display-4 text-center text-uppercase">Aggregate issues for a composer repository</h1>
    <p class="lead">
        Some project are split up into multiple packages which makes it harder to get an overview of open issues.
        This little utility helps you to get a full list of issues from root requirements of a given package.
    </p>
    <hr class="my-4">

    <div class="card mb-3">
        <div class="card-header bg-warning">
            Early state notice
        </div>
        <div class="card-body">
            <p class="card-text">
                This tool is in a <b>prototypical</b> state. You will most likely encounter some bugs. Please file me an issue if you found one.
            </p>

            <a class="btn btn-secondary" target="_blank" href="https://github.com/icanhazstring/github-issue-aggregator/issues/new">
                <i class="fab fa-github"></i>
                File an issue
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <p>To use this aggregation you will need to login with Github.</p>
            <form method="get" action="https://github.com/login/oauth/authorize">
                <input type="hidden" name="scope" value="user:email"/>
                <input type="hidden" name="client_id" value="<?= $this->e($clientId) ?>"/>
                <button class="btn btn-primary btn-lg">
                    <i class="fab fa-github"></i>
                    Login with Github
                </button>
            </form>
        </div>
    </div>

</div>
