language: php
php:
- 7.1

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  fast_finish: true

services:
  - redis-server

before_script:
 - composer install --no-interaction

script:
 - composer check
